### ISSUE TITLE
CMake imported target leaks C++14 requirement

### ISSUE THREAD

**Issue by zakalawe** [getsentry/sentry-native#221]
The generated sentry-targets.cmake specifies 'INTERFACE_COMPILE_FEATURES "cxx_std_14"', which is causing me some difficulties. It's no problem for me to build the sentry libs using a C++14 compiler, but I don't want to switch my entire application to use it (currently on C++11)

Is it intentional that C++14 requirement (from Crashpad) is exposed as an interface feature? Given that sentry.h exposes a C API, this seems strange.

**Comment by zakalawe** [comment]
As an experiment, I tried removing the INTERFACE_COMPILE_FEATURES from the cmake file, and at least on macOS (Xcode 11.4, Apple clang version 11.0.3 (clang-1103.0.32.29)) everything builds and links fine. I'm about to start testing the Windows integration

**Comment by Swatinem** [comment]
I think this is already fixed in master, can you try with that?

CC @madebr

**Comment by zakalawe** [comment]
Thanks, I was using the latest stable release, will try master and report back.

**Comment by madebr** [comment]
I think it's still present.
I removed it in sentry-native in https://github.com/getsentry/sentry-native/commit/7b18bef0b7cdc258c4baf17a4903fa0a44b905c3#diff-af3b638bc2a3e6c650974192a53c7291
And added it to crashpad: https://github.com/getsentry/crashpad/blob/23474e346aa7c24a27506ee038b22bae74a5ce75/client/CMakeLists.txt#L60

It can be fixed by surrounding cxx_std_14 with the BUILD_INTERFACE generator expression

**Comment by zakalawe** [comment]
@madebr I'm seeing a different issue on master, which is blocking me reporting on this. What I have in my CmakeList for my target is:

  find_package(sentry)
  target_link_libraries(myFooTarget sentry::sentry)

This was working with the stable release (0.2.2). With master, CMake fails to process, with the following message:

> CMake Error at src/Main/CMakeLists.txt:83 (add_executable):
  Target "myFooTarget" links to target "sentry_crashpad::client" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

Of course there is no such thing as 'sentry_crashpad::client' defined in any of the exported Cmake files.

**Comment by zakalawe** [comment]
Ah figure out the issue, sentry_targets.cmake contains the following:

> # Create imported target sentry::sentry
add_library(sentry::sentry SHARED IMPORTED)

set_target_properties(sentry::sentry PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SENTRY_WITH_UNWINDER_LIBBACKTRACE"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<\$<OR:\$<PLATFORM_ID:Linux>,\$<PLATFORM_ID:Android>>:-Wl,--build-id=sha1>;sentry_crashpad::client"
)

This seems weird since I'm on a macOS build using the 'internal' crashpad included as a submodule.

**Comment by madebr** [comment]
@zakalawe 
The `sentry_crashpad::client` target is created by`sentry_crashpad-targets.cmake` (when you're building static libraries).
Have you tried updating the git submodules? Because these `sentry_native` targets are a recent addition.
Run `git fetch origin` and `git submodule update -r -f` inside the `sentry-native` directory to force updating them recursively.

If that doesn't work, can you post the files in the cmake folder of your installed `sentry-native` to a gist (as not to pollute this issue with a lot of output).
I don't own a mac so I can't test a similar setup.

@Swatinem 
It looks like the defines `SENTRY_WITH_UNWINDER_LIBBACKTRACE` are exported,
I guess these defines can be made private?

**Comment by Swatinem** [comment]
> It looks like the defines `SENTRY_WITH_UNWINDER_LIBBACKTRACE` are exported,
> I guess these defines can be made private?

Yes I think so.

**Comment by zakalawe** [comment]
@madebr  I think the confusion occurring is static-vs-shared libs. My CMake build of sentry was configure with no options aside from CMAKE_INSTALL_PREFIX. It's defaulted to building:
- Crashpad library static (as libcrashpad_client.a)
- libSentry as shared aka dynamic (libsentry.dylib)

And at cmake install time, libSentry.dylib is installed to $prefix/lib/ of course - but Crashpad libraries are not (because they're static).

Given this (which seems correct to me), these lines seem weird to me:
`target_link_libraries(sentry PUBLIC
			$<BUILD_INTERFACE:crashpad::client>
			$<INSTALL_INTERFACE:sentry_crashpad::client>
		)`

If libSentry *and* libCrashpad were static, it would make sense (libCrashpad is needed transitively by applications linking to libSentry). But I think for the case of a dynamic libSentry, 'PUBLIC' is the wrong specification here: it's a PRIVATE dependency. 

(This would also hold if libCrashpad were built dynamic, since the dynamic linker would deal with the transitive dependency, and libSentry users do not need to link directly to libCrashpad symbols)

Of course, I'm still figuring this out, could be totally mistaken about how it's intended to work.

**Comment by zakalawe** [comment]
As a test, I changed PUBLIC -> PRIVATE in the line above (root CMakeList.txt, line 287), and the generated sentry-targets.cmake now looks correct & works for me.

**Comment by Swatinem** [comment]
That definitely makes sense, since crashpad is linked statically to sentry, so it does not need to be exported.

**Comment by zakalawe** [comment]
I was unsure if there was a static configuration option (common in many CMake projects) where libSentry itself was built static. In that situation, the current version could make sense.

**Comment by madebr** [comment]
@zakalawe 
You're right about `CMakelists.txt:287`. That link connection should indeed be made `PRIVATE`.
For a static `sentry` library, nothing will change. Users will have to link to sentry and all of its dependent static libraries.
But currently, a consumer of a shared `sentry` library will also link to the crashpad client, which is unnecessary.

**Comment by zakalawe** [comment]
@madebr yes this sounds good to me, and my original issue is solved as well - thanks.
